version: "3.9"

services:
  mysql_university_admission:
    image: mysql:8.0
    container_name: mysql_university_admission
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - university_admission-network
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - university_admission-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"] # Command to check health.
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.

  university_admission:
    image: university_admission:latest
    container_name: university_admission
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - university_admission-network
    environment:
      MYSQL_HOST: "mysql_university_admission"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    depends_on:
      mysql_university_admission:
        condition: service_healthy
    restart: always

networks:
  university_admission-network:
    driver: bridge

volumes:
  university_admission-data:
    driver: local
