# Node.js CI workflow to install dependencies, run linting, check formatting, and test code
name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js and cache dependencies
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run linting
      - name: Run ESLint
        run: npm run lint

      # Step 5: Run tests
      - name: Run Jest tests
        run: npm test

      # Step 6: Check Code Formatting with Prettier
      - name: Check Code Formatting
        run: npm run prettier:check
